# Buildpack API version
api = "0.7"

# Buildpack ID and metadata
[buildpack]
id = "initializ-buildpacks/elixir"
version = "0.0.1"
name = "Initializ buildpack for Elixir"

# Stacks that the buildpack will work with
[[stacks]]
id = "Initializ Distroless Stack"

# Types configuration
[[types]]
build = true
cache = true
launch = true

