# Buildpack API version
api = "0.7"

# Buildpack ID and metadata
[buildpack]
id = "app.elixir-buildpack"
version = "0.0.1"
name = "Elixir Buildpack"

# Stacks that the buildpack will work with
[[stacks]]
id = "Initializ Distroless Stack"

# Types configuration
[[types]]
build = true
cache = true
launch = true

